//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGymProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Departman
    {
        public Departman()
        {
            this.Personal = new HashSet<Personal>();
        }
    
        public int id { get; set; }

        [Display(Name = "Departman Adý")]
        [Required(ErrorMessage = "Lütfen Bir Departman Adý Giriniz !")]
        public string DepartmanAd { get; set; }
    
        public virtual ICollection<Personal> Personal { get; set; }
    }
}
