//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGymProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personal
    {
        public int id { get; set; }

        [Display(Name = "Departman Adý")]
        [Required(ErrorMessage = "Lütfen Bir Departman Seçiniz !")]
        public Nullable<int> DepartmanId { get; set; }

        [Required(ErrorMessage = "Ad Alaný Zorunludur !")]
        public string Ad { get; set; }

        [Required(ErrorMessage = "Soyad Alaný Zorunludur !")]
        public string Soyad { get; set; }

        [Display(Name = "Maaþ")]
        [Range(1399, 30000, ErrorMessage = "Maaþ Alaný 1400 ila 30000 TL Arasýnda Olmalý !")]
        public Nullable<short> Maas { get; set; }

        [Required(ErrorMessage = "Cinsiyet Alaný Zorunludur !")]
        public bool Cinsiyet { get; set; }

        [Display(Name = "Evlilik Durumu")]
        [Required(ErrorMessage = "Evlilik Durumu Alaný Zorunludur !")]
        public bool EvliMi { get; set; }

        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Doðum Tarihi Alaný Zorunludur !")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
