//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGymProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.User = new HashSet<User>();
        }
    
        public short RolId { get; set; }
        public string RolAd { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
